### PR TITLE
feat(rules): no-useless-rename no-param-reassign, BREAKING CHANGE

### PR DESCRIPTION
**Pull request by MrSwitch**
# Proposed 

- [`no-param-reassign`](https://eslint.org/docs/rules/no-param-reassign)
- [`no-useless-rename`](https://eslint.org/docs/rules/no-useless-rename)
- [`strict`](https://eslint.org/docs/rules/strict)
- [`array-bracket-newline: [2, "consistent"]`](https://eslint.org/docs/rules/array-bracket-newline)
- [`array-element-newline: [2, "consistent"]`](https://eslint.org/docs/rules/array-element-newline)
- [`no-tabs: [2, {"allowIndentationTabs": true}]`](https://eslint.org/docs/rules/no-tabs)
- [`spaced-comment: [2, "always"]`](https://eslint.org/docs/rules/spaced-comment)
- [`template-curly-spacing`](https://eslint.org/docs/rules/template-curly-spacing)

out of...

# `eslint:all` ([eslint summary](https://www.npmjs.com/package/eslint-formatter-summary))

 ✨  Summary of failing ESLint rules  

Errors | Rule
--|--
146 | [strict](https://eslint.org/docs/rules/strict)
880 | [capitalized-comments](https://eslint.org/docs/rules/capitalized-comments)
5073 | [function-call-argument-newline](https://eslint.org/docs/rules/function-call-argument-newline)
289 | [line-comment-position](https://eslint.org/docs/rules/line-comment-position)
297 | [no-inline-comments](https://eslint.org/docs/rules/no-inline-comments)
4217 | [max-len](https://eslint.org/docs/rules/max-len)
16489 | [padded-blocks](https://eslint.org/docs/rules/padded-blocks)
71216 | [no-tabs](https://eslint.org/docs/rules/no-tabs)
219 | [eol-last](https://eslint.org/docs/rules/eol-last)
942 | [func-style](https://eslint.org/docs/rules/func-style)
226 | [init-declarations](https://eslint.org/docs/rules/init-declarations)
27 | [global-require](https://eslint.org/docs/rules/global-require)
1496 | [id-length](https://eslint.org/docs/rules/id-length)
3604 | [camelcase](https://eslint.org/docs/rules/camelcase)
420 | [multiline-comment-style](https://eslint.org/docs/rules/multiline-comment-style)
167 | [require-await](https://eslint.org/docs/rules/require-await)
5009 | [sort-keys](https://eslint.org/docs/rules/sort-keys)
1329 | [array-element-newline](https://eslint.org/docs/rules/array-element-newline)
257 | [prefer-destructuring](https://eslint.org/docs/rules/prefer-destructuring)
2202 | [object-property-newline](https://eslint.org/docs/rules/object-property-newline)
137 | [consistent-return](https://eslint.org/docs/rules/consistent-return)
468 | [no-extra-parens](https://eslint.org/docs/rules/no-extra-parens)
120 | [curly](https://eslint.org/docs/rules/curly)
132 | [no-process-env](https://eslint.org/docs/rules/no-process-env)
1381 | [multiline-ternary](https://eslint.org/docs/rules/multiline-ternary)
774 | [no-ternary](https://eslint.org/docs/rules/no-ternary)
169 | [array-bracket-newline](https://eslint.org/docs/rules/array-bracket-newline)
161 | [function-paren-newline](https://eslint.org/docs/rules/function-paren-newline)
40 | [lines-around-comment](https://eslint.org/docs/rules/lines-around-comment)
453 | [max-lines-per-function](https://eslint.org/docs/rules/max-lines-per-function)
365 | [max-statements](https://eslint.org/docs/rules/max-statements)
204 | [template-curly-spacing](https://eslint.org/docs/rules/template-curly-spacing)
58 | [require-atomic-updates](https://eslint.org/docs/rules/require-atomic-updates)
38 | [max-params](https://eslint.org/docs/rules/max-params)
2615 | [no-magic-numbers](https://eslint.org/docs/rules/no-magic-numbers)
173 | [no-shadow](https://eslint.org/docs/rules/no-shadow)
76 | [new-cap](https://eslint.org/docs/rules/new-cap)
276 | [no-implicit-coercion](https://eslint.org/docs/rules/no-implicit-coercion)
31 | [no-warning-comments](https://eslint.org/docs/rules/no-warning-comments)
53 | [callback-return](https://eslint.org/docs/rules/callback-return)
51 | [no-negated-condition](https://eslint.org/docs/rules/no-negated-condition)
92 | [prefer-named-capture-group](https://eslint.org/docs/rules/prefer-named-capture-group)
219 | [require-unicode-regexp](https://eslint.org/docs/rules/require-unicode-regexp)
207 | [arrow-body-style](https://eslint.org/docs/rules/arrow-body-style)
50 | [no-else-return](https://eslint.org/docs/rules/no-else-return)
4 | [no-lone-blocks](https://eslint.org/docs/rules/no-lone-blocks)
3 | [handle-callback-err](https://eslint.org/docs/rules/handle-callback-err)
175 | [no-undefined](https://eslint.org/docs/rules/no-undefined)
34 | [no-unused-expressions](https://eslint.org/docs/rules/no-unused-expressions)
45 | [max-lines](https://eslint.org/docs/rules/max-lines)
21 | [guard-for-in](https://eslint.org/docs/rules/guard-for-in)
59 | [no-empty-function](https://eslint.org/docs/rules/no-empty-function)
14 | [max-classes-per-file](https://eslint.org/docs/rules/max-classes-per-file)
76 | [class-methods-use-this](https://eslint.org/docs/rules/class-methods-use-this)
13 | [lines-between-class-members](https://eslint.org/docs/rules/lines-between-class-members)
141 | [no-param-reassign](https://eslint.org/docs/rules/no-param-reassign)
592 | [no-underscore-dangle](https://eslint.org/docs/rules/no-underscore-dangle)
53 | [func-names](https://eslint.org/docs/rules/func-names)
32 | [no-invalid-this](https://eslint.org/docs/rules/no-invalid-this)
1 | [consistent-this](https://eslint.org/docs/rules/consistent-this)
87 | [implicit-arrow-linebreak](https://eslint.org/docs/rules/implicit-arrow-linebreak)
208 | [spaced-comment](https://eslint.org/docs/rules/spaced-comment)
94 | [prefer-object-spread](https://eslint.org/docs/rules/prefer-object-spread)
4 | [block-spacing](https://eslint.org/docs/rules/block-spacing)
11 | [no-multi-assign](https://eslint.org/docs/rules/no-multi-assign)
15 | [no-sync](https://eslint.org/docs/rules/no-sync)
13 | [prefer-promise-reject-errors](https://eslint.org/docs/rules/prefer-promise-reject-errors)
83 | [no-plusplus](https://eslint.org/docs/rules/no-plusplus)
2 | [no-buffer-constructor](https://eslint.org/docs/rules/no-buffer-constructor)
10 | [no-bitwise](https://eslint.org/docs/rules/no-bitwise)
1726 | [sort-imports](https://eslint.org/docs/rules/sort-imports)
88 | [newline-per-chained-call](https://eslint.org/docs/rules/newline-per-chained-call)
52 | [operator-linebreak](https://eslint.org/docs/rules/operator-linebreak)
64 | [no-mixed-operators](https://eslint.org/docs/rules/no-mixed-operators)
10 | [space-unary-ops](https://eslint.org/docs/rules/space-unary-ops)
6 | [no-lonely-if](https://eslint.org/docs/rules/no-lonely-if)
5 | [semi-style](https://eslint.org/docs/rules/semi-style)
43 | [no-return-assign](https://eslint.org/docs/rules/no-return-assign)
12 | [default-param-last](https://eslint.org/docs/rules/default-param-last)
8 | [default-case](https://eslint.org/docs/rules/default-case)
8 | [no-nested-ternary](https://eslint.org/docs/rules/no-nested-ternary)
5 | [no-useless-concat](https://eslint.org/docs/rules/no-useless-concat)
12 | [complexity](https://eslint.org/docs/rules/complexity)
4 | [nonblock-statement-body-position](https://eslint.org/docs/rules/nonblock-statement-body-position)
7 | [wrap-regex](https://eslint.org/docs/rules/wrap-regex)
6 | [new-parens](https://eslint.org/docs/rules/new-parens)
1 | [operator-assignment](https://eslint.org/docs/rules/operator-assignment)
7 | [no-continue](https://eslint.org/docs/rules/no-continue)
9 | [max-depth](https://eslint.org/docs/rules/max-depth)
2 | [no-new](https://eslint.org/docs/rules/no-new)
1 | [no-useless-constructor](https://eslint.org/docs/rules/no-useless-constructor)
3 | [no-undef-init](https://eslint.org/docs/rules/no-undef-init)
2 | [wrap-iife](https://eslint.org/docs/rules/wrap-iife)
9 | [no-process-exit](https://eslint.org/docs/rules/no-process-exit)
6 | [func-name-matching](https://eslint.org/docs/rules/func-name-matching)
54 | [computed-property-spacing](https://eslint.org/docs/rules/computed-property-spacing)
1 | [no-dupe-else-if](https://eslint.org/docs/rules/no-dupe-else-if)
9 | [no-useless-computed-key](https://eslint.org/docs/rules/no-useless-computed-key)
1 | [object-curly-newline](https://eslint.org/docs/rules/object-curly-newline)

🔥  126799 problems in total (126799 errors, 0 warnings)

### CODE REVIEW

**Comment by mariocoski** [comment]
You want to throw all of these rules at once? and then deal with it in dashboard in one go?

**Comment by MrSwitch** [comment]
> You want to throw all of these rules at once? and then deal with it in dashboard in one go?

Just the 8 top proposed rules, most will be fixed with `eslint --fix` flag.

- `no-param-reassign` will be manual - it has around 141 conflicts.
- `no-tabs: [2, {"allowIndentationTabs": true}]` could be done with a Regex in an IDE

We can also ignore rules to fix up later e.g. Like we do with [`no-throw-literal: 0`](https://github.com/5app/dashboard/blob/master/.eslintrc.json#L8)

**Comment by MrSwitch** [comment]
@5app/devs does anyone want to add any more rules whilst we're at it?

I'm thinking i might include...

Errors | Rule
--|--
27 | [global-require](https://eslint.org/docs/rules/global-require)
76 | [new-cap](https://eslint.org/docs/rules/new-cap)
53 | [callback-return](https://eslint.org/docs/rules/callback-return)
3 | [handle-callback-err](https://eslint.org/docs/rules/handle-callback-err)
2 | [no-buffer-constructor](https://eslint.org/docs/rules/no-buffer-constructor)
2 | [no-new](https://eslint.org/docs/rules/no-new)
6 | [func-name-matching](https://eslint.org/docs/rules/func-name-matching)
1 | [no-dupe-else-if](https://eslint.org/docs/rules/no-dupe-else-if)
9 | [no-useless-computed-key](https://eslint.org/docs/rules/no-useless-computed-key)

**Comment by diondiondion** [comment]
> does anyone want to add any more rules whilst we're at it?

[jsx-curly-brace-presence](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md) could be nice (set to `"never"`), to prevent JSX like `<Comp prop={'string'} />` and turn it into `<Comp prop="string" />`

**Comment by MrSwitch** [comment]
> > does anyone want to add any more rules whilst we're at it?
> 
> [jsx-curly-brace-presence](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md) could be nice (set to `"never"`), to prevent JSX like `<Comp prop={'string'} />` and turn it into `<Comp prop="string" />`

We've not added the React Plugin perhaps create an issue.

**Comment by mariocoski** [comment]
As per discussion in: https://github.com/5app/dashboard/issues/7483

I would discuss whether we should use: 
https://eslint.org/docs/rules/camelcase

what do you think @5app/devs ?

it might be done as a separate improvement as expect a lot to refactor...

**Comment by MrSwitch** [comment]
> https://eslint.org/docs/rules/camelcase
> it might be done as a separate improvement as expect a lot to refactor...

"3604" camelcase changes ☕️

**Comment by diondiondion** [comment]
> what do you think @5app/devs ?

I've always been for it – I think the main counter argument was consistency with the DB fields.

(Semi-related side note/rant: The bigger issue IMO is the rampant inconsistency in the data structure of objects that we're working with in the frontend. E.g. sometimes a `user` object will have an `id` field and sometimes `user_id`, sometimes the email field will be `name`, sometimes `email`, etc. There's a ticket to address this for assets and playlists (https://github.com/5app/dashboard/issues/4785), but I wonder if we couldn't take a more holistic approach to this and unify & verify all of this at a higher level, somehow. I don't really know what's best practice in this space, just that there's got to be a better way.)

**Comment by mariocoski** [comment]
To solve the issue with casing many companies using js stack and providing RESTful apis:
- java script (front-end) use camelCase for most of the stuff, SNAKE_CASE for 'real' constants
- RESTful interfaces (in/out) - { snake_case: { nested_snake_case: { } } } for request body and response body
- java script (back-end) use camelCase for most of the stuff, SNAKE_CASE for 'real' constants
- for database tier (snake_case)

To provide more holistic approach to conversions we could use helpers which does this recursively, there are many libraries out there.

I have been using one with success:
https://github.com/kube-js/kube-ts-server/blob/f8963ce63038e1d2fa7864c6d56aca00e2262a43/src/presenter/express/api/v1/routes/auth/register/index.ts#L28
https://github.com/kube-js/kube-ts-server/blob/f8963ce63038e1d2fa7864c6d56aca00e2262a43/src/presenter/express/api/v1/routes/auth/register/index.ts#L70

**Pull request merged**
